import { defineConfig } from 'astro/config';

import tailwind from "@astrojs/tailwind";

// https://astro.build/config
/*
export default defineConfig({
  integrations: [tailwind()],
  // The value for site must be one of the following: https://<username>.github.io || The random URL autogenerated for a GitHub Organization’s.
  site: 'https://level11software.github.io',
  // A value for base may be required so that Astro will treat your repository name (e.g. /my-repo) as the root of your website.
  base: '/level11-software-landing-page-ai'
});

*/


// CUSTOM DOMAIN
export default defineConfig({
  integrations: [tailwind()],
  // The value for site must be one of the following: https://<username>.github.io || The random URL autogenerated for a GitHub Organization’s.
  site: 'https://level11.software',
});